### ISSUE TITLE
Can I use it in production environment?

### ISSUE THREAD

**Issue by JerryBian** [ddobric/ServiceBusJavaScriptSdk#1]
First of all, awesome job. We want to use Service Bus in JavaScript font end environment, this library seems the only one choice for us. We also tried to use Node library, it seems very hard to use and it cause the script size huge large.

What we want to know is what license of this library, can we use it in production environment? From this page http://developers.de/blogs/damir_dobric/archive/2014/08/12/jumpstart-azure-service-bus-javascript-sdk.aspx, this library is coordinated with Microsoft Service Bus team, what does it mean?

Thanks a lot.

**Comment by ddobric** [comment]
Hi Jerry,

You Can use it in production environment.   It is license free, but without support. If there are problems you can contact me.
Coordinated means we scheduled it together (daenet+ MS). We did the client side and they made CORS possible on server side.

Sent from my Windows Phone
